# Generated by Django 5.1.3 on 2024-11-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_auto_20200508_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherextra',
            name='department',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
